name: Python Pylint Check

on:
  push:
    branches:
      - main  # Замените "main" на вашу основную ветку

jobs:
  pylint:
    name: Run Pylint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11  # Укажите версию Python, которую вы используете

    - name: Install dependencies
      run: pip3 install pylint

    - name: Run pylint
      run: |
        echo -e '"""Temp file for Github Action"""\n' > __init__.py
        pylint --disable=R,C ${PWD} > pylint_output.txt
        if ! grep -q "Your code has been rated at 10.00/10" pylint_output.txt; then
          echo "Pylint issues found!"
          cat pylint-output.txt
          exit 1
        fi
      continue-on-error: true

    - name: Check pylint results
      run: echo "Pylint check passed"

    - name: Fail if pylint issues found
      run: |
        if [ -n "$(find . -name '*.pylint')" ]; then
          echo "Pylint issues found!"
          find . -name '*.pylint' -exec cat {} \;
          exit 1
        fi
